  joint_blw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: dextrobot_b_back_left_wheel_joint
  joint_brw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: dextrobot_b_back_right_wheel_joint
  joint_frw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: dextrobot_b_front_right_wheel_joint
  joint_flw_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: dextrobot_b_front_left_wheel_joint

#joint_pan_position_controller:
#  type: position_controllers/JointPositionController
#  joint: joint_camera_pan
#joint_tilt_position_controller:
#  type: position_controllers/JointPositionController
#  joint: joint_camera_tilt

  robotnik_base_control:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : ['dextrobot_b_front_left_wheel_joint','dextrobot_b_back_left_wheel_joint']
    right_wheel : ['dextrobot_b_front_right_wheel_joint','dextrobot_b_back_right_wheel_joint']
    publish_rate: 50.0              
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.543 #def 0.433
    wheel_radius : 0.110 #def 0.0762

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25

    # Base frame_id
    base_frame_id: dextrobot_b_base_footprint
    odom_frame_id: dextrobot_b_odom
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.5 # m/s
        min_velocity           : -1.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 3.00  # m/s^2
        min_acceleration       : -3.00 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.0  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 3.0  # rad/s^2


  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0



