local_costmap:
  global_frame: /dextrobot_odom
  robot_base_frame: /dextrobot_base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 8.0 
  height: 8.0 
  footprint_padding: 0.0

 
